-- src/obf/checksum.lua
-- Shared integrity-checksum core for the anti-tamper pass (FEAT-005).
--
-- This module is used at OBFUSCATION time to compute an expected checksum over
-- the critical embedded blob of each virtualized function: its PHYSICAL
-- instruction arrays (the per-build-encoded VM bytecode). The exact same fold
-- is emitted into the output (see src/runtime/guards.lua and the guard prelude
-- generated by src/obf/passes/antitamper.lua) and recomputed at RUNTIME over
-- the embedded proto.c table. If any byte of the virtualized bytecode (or the
-- embedded expected value) is flipped, the recomputed checksum no longer
-- matches and the guard fires tamper_response().
--
-- Compatibility: Lua-5.1-compatible, pure arithmetic only (floor / % / * ), no
-- bit32, no 5.4-only bitwise operators, no integer division. Reuses the same
-- u32 / mul32 primitives as src/obf/cipher.lua so results are byte-identical on
-- Lua 5.1, Lua 5.4 and LuaJIT 2.1.
--
-- The fold is parameterized by three per-build (seeded) constants (seed, m1,
-- m2) so two builds with different seeds use different checksum parameters.

local cipher = require("obf.cipher")

local checksum = {}

local u32 = cipher.u32
local mul32 = cipher.mul32

-- Fold a flat list of instruction arrays (each a list of numbers) into a 32-bit
-- checksum. `code` is proto.c: an array of arrays. `nfields` is the number of
-- physical slots per instruction (enc.NFIELDS). (seed, m1, m2) are the per-build
-- parameters. Values may be negative (RK constant refs are encoded negative);
-- Lua's `%` is floored on all three runtimes, so (v % 65521) is identical
-- everywhere and maps negatives into [0, 65520].
function checksum.fold_code(code, nfields, seed, m1, m2)
  local h = u32(seed)
  for ci = 1, #code do
    local ins = code[ci]
    for si = 1, nfields do
      local v = ins[si] or 0
      h = u32(mul32(h, m1) + (v % 65521) + 1)
      h = u32(h + math.floor(h / 65536))
    end
    -- mix in the instruction index so reordering is also detected
    h = u32(h + mul32(ci, 2654435761))
  end
  h = u32(mul32(h, m2))
  h = u32(h + math.floor(h / 256))
  return u32(h)
end

return checksum
